services:
  OAS:
    ports:
      - "${OAS_PORT:-22267}:${OAS_PORT:-22267}"
    volumes:
      - '.:/app/OnmyojiAutoScript:rw'
    container_name: 'oas-env'
    image: 'oas-env'
    environment:
      - TZ=Asia/Shanghai
    build:
      context: ./deploy/docker/
      dockerfile: ./Dockerfile
    restart: unless-stopped
